### ISSUE TITLE
Skill graph starting at 0?

### ISSUE THREAD

**Issue by yavorh** [NS2CDT/NS2Plus#9]
Hi, can you pleasee start the skill graph y axis @ 0? It can be very confusing at time at a quick look, cause it looks like a team gained/lost half the skill points during a round. 

At least if it was an option, thanks!

**Comment by GhoulofGSG9** [comment]
The issue with starting the axis with 0 is that the difference between the teams average values becomes hard to read specially when both teams have an average of more than 2000. Yes it may be misleading at first glance but scaling the axis to the actual range of values improves readability otherwise.
